// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VEGG.TABLE.Infrastructure.Data;

#nullable disable

namespace VEGG.TABLE.Infrastructure.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20260604092414_AddFarmOwnerRelationship")]
    partial class AddFarmOwnerRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VEGG.TABLE.Core.Entities.Farm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Farms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Lat = 51.533200000000001,
                            Lng = -0.063200000000000006,
                            Name = "Hackney City Farm",
                            OwnerId = 1
                        },
                        new
                        {
                            Id = 2,
                            Lat = 51.498800000000003,
                            Lng = -0.041599999999999998,
                            Name = "Surrey Docks Farm",
                            OwnerId = 2
                        },
                        new
                        {
                            Id = 3,
                            Lat = 51.547800000000002,
                            Lng = -0.14560000000000001,
                            Name = "Kentish Town City Farm",
                            OwnerId = 3
                        },
                        new
                        {
                            Id = 4,
                            Lat = 51.519500000000001,
                            Lng = -0.064500000000000002,
                            Name = "Spitalfields Farm",
                            OwnerId = 4
                        },
                        new
                        {
                            Id = 5,
                            Lat = 51.422499999999999,
                            Lng = -0.063500000000000001,
                            Name = "Crystal Palace Park Farm",
                            OwnerId = 5
                        });
                });

            modelBuilder.Entity("VEGG.TABLE.Core.Entities.Produce", b =>
                {
                    b.Property<int>("ProduceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProduceId"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLiked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPurchased")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotograghPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("ProduceId");

                    b.ToTable("ProduceTable");

                    b.HasData(
                        new
                        {
                            ProduceId = 1,
                            Category = 9,
                            Description = "Plums for sale",
                            IsLiked = false,
                            IsOnSale = false,
                            IsPurchased = false,
                            Name = "Plums",
                            PhotograghPath = "",
                            Price = 2.0,
                            Stock = 1,
                            UserId = 1,
                            Weight = 2.0
                        },
                        new
                        {
                            ProduceId = 2,
                            Category = 9,
                            Description = "Fresh apples for sale",
                            IsLiked = true,
                            IsOnSale = false,
                            IsPurchased = false,
                            Name = "Apples",
                            PhotograghPath = "",
                            Price = 1.5,
                            Stock = 5,
                            UserId = 1,
                            Weight = 3.0
                        },
                        new
                        {
                            ProduceId = 3,
                            Category = 9,
                            Description = "Organic bananas",
                            IsLiked = false,
                            IsOnSale = true,
                            IsPurchased = false,
                            Name = "Bananas",
                            PhotograghPath = "",
                            Price = 0.98999999999999999,
                            Stock = 10,
                            UserId = 2,
                            Weight = 2.0
                        },
                        new
                        {
                            ProduceId = 4,
                            Category = 9,
                            Description = "Crunchy carrots for cooking",
                            IsLiked = false,
                            IsOnSale = false,
                            IsPurchased = true,
                            Name = "Carrots",
                            PhotograghPath = "",
                            Price = 1.2,
                            Stock = 7,
                            UserId = 2,
                            Weight = 4.0
                        },
                        new
                        {
                            ProduceId = 5,
                            Category = 9,
                            Description = "Juicy red tomatoes",
                            IsLiked = true,
                            IsOnSale = true,
                            IsPurchased = false,
                            Name = "Tomatoes",
                            PhotograghPath = "",
                            Price = 2.75,
                            Stock = 8,
                            UserId = 3,
                            Weight = 3.0
                        },
                        new
                        {
                            ProduceId = 6,
                            Category = 9,
                            Description = "Farm fresh potatoes",
                            IsLiked = false,
                            IsOnSale = false,
                            IsPurchased = false,
                            Name = "Potatoes",
                            PhotograghPath = "",
                            Price = 3.0,
                            Stock = 15,
                            UserId = 3,
                            Weight = 10.0
                        },
                        new
                        {
                            ProduceId = 7,
                            Category = 9,
                            Description = "Sweet strawberries",
                            IsLiked = true,
                            IsOnSale = true,
                            IsPurchased = true,
                            Name = "Strawberries",
                            PhotograghPath = "",
                            Price = 4.5,
                            Stock = 6,
                            UserId = 4,
                            Weight = 1.0
                        },
                        new
                        {
                            ProduceId = 8,
                            Category = 9,
                            Description = "Fresh green lettuce",
                            IsLiked = false,
                            IsOnSale = false,
                            IsPurchased = false,
                            Name = "Lettuce",
                            PhotograghPath = "",
                            Price = 1.1000000000000001,
                            Stock = 4,
                            UserId = 4,
                            Weight = 1.0
                        },
                        new
                        {
                            ProduceId = 9,
                            Category = 9,
                            Description = "Citrus oranges for juice",
                            IsLiked = true,
                            IsOnSale = false,
                            IsPurchased = true,
                            Name = "Oranges",
                            PhotograghPath = "",
                            Price = 2.2999999999999998,
                            Stock = 12,
                            UserId = 5,
                            Weight = 5.0
                        },
                        new
                        {
                            ProduceId = 10,
                            Category = 9,
                            Description = "Cool fresh cucumbers",
                            IsLiked = false,
                            IsOnSale = true,
                            IsPurchased = false,
                            Name = "Cucumbers",
                            PhotograghPath = "",
                            Price = 1.8,
                            Stock = 9,
                            UserId = 5,
                            Weight = 2.0
                        });
                });

            modelBuilder.Entity("VEGG.TABLE.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "bossman@live.co.uk",
                            Name = "VegManDan",
                            Password = "$2a$11$.L.EhNZir7n.hylCEenduOkBlqrdyXHt0jtDqMrW46jy0.pKbkMw2",
                            UserType = 0
                        },
                        new
                        {
                            Id = 2,
                            Email = "contact@fresh.co.uk",
                            Name = "FreshFarmers",
                            Password = "$2a$11$G7VbY4W8z1zW7F4Q1j6Qj.qH8zM8G.VzS6LhZ9KqW.0f2gQ8m8hXy",
                            UserType = 0
                        },
                        new
                        {
                            Id = 3,
                            Email = "info@londongreens.co.uk",
                            Name = "LondonGreens",
                            Password = "$2a$11$uK8fS9j2lK7mN4Q2x5P5e.rJ0hZ7G.VzS6LhZ9KqW.0f2gQ8m8hXy",
                            UserType = 0
                        },
                        new
                        {
                            Id = 4,
                            Email = "hello@spital.co.uk",
                            Name = "SpitalFieldsOrg",
                            Password = "$2a$11$vN2mX5Q8k1jL4H3x6T9a.rJ0hZ7G.VzS6LhZ9KqW.0f2gQ8m8hXy",
                            UserType = 0
                        },
                        new
                        {
                            Id = 5,
                            Email = "team@crystalveg.co.uk",
                            Name = "CrystalVeg",
                            Password = "$2a$11$wL3bV8k9m2pQ5D4y7R1b.rJ0hZ7G.VzS6LhZ9KqW.0f2gQ8m8hXy",
                            UserType = 0
                        },
                        new
                        {
                            Id = 6,
                            Email = "buyer1@test.com",
                            Name = "GreenShopper",
                            Password = "$2a$11$G7VbY4W8z1zW7F4Q1j6Qj.qH8zM8G.VzS6LhZ9KqW.0f2gQ8m8hXy",
                            UserType = 1
                        },
                        new
                        {
                            Id = 7,
                            Email = "buyer2@test.com",
                            Name = "OrganicFan",
                            Password = "$2a$11$fK5Qz7n.uV.z8L3M9KqW.0f2gQ8m8hXyLhZ9KqW.0f2gQ8m8hXy",
                            UserType = 1
                        });
                });

            modelBuilder.Entity("VEGG.TABLE.Core.Entities.UserProduceLike", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ProduceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LikedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "ProduceId");

                    b.HasIndex("ProduceId");

                    b.ToTable("LikedTable");
                });

            modelBuilder.Entity("VEGG.TABLE.Core.Entities.Farm", b =>
                {
                    b.HasOne("VEGG.TABLE.Core.Entities.User", "Owner")
                        .WithMany("Farms")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("VEGG.TABLE.Core.Entities.UserProduceLike", b =>
                {
                    b.HasOne("VEGG.TABLE.Core.Entities.Produce", "Produce")
                        .WithMany()
                        .HasForeignKey("ProduceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VEGG.TABLE.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produce");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VEGG.TABLE.Core.Entities.User", b =>
                {
                    b.Navigation("Farms");
                });
#pragma warning restore 612, 618
        }
    }
}
