// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VEGG.TABLE.Infrastructure.Data;

#nullable disable

namespace VEGG.TABLE.Infrastructure.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20260603003222_UpdateSeedData")]
    partial class UpdateSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VEGG.TABLE.Core.Entities.Produce", b =>
                {
                    b.Property<int>("ProduceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProduceId"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLiked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPurchased")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotograghPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("ProduceId");

                    b.ToTable("ProduceTable");

                    b.HasData(
                        new
                        {
                            ProduceId = 1,
                            Category = 9,
                            Description = "Plums for sale",
                            IsLiked = false,
                            IsOnSale = false,
                            IsPurchased = false,
                            Name = "Plums",
                            PhotograghPath = "",
                            Price = 2.0,
                            Stock = 1,
                            UserId = 1,
                            Weight = 2.0
                        },
                        new
                        {
                            ProduceId = 2,
                            Category = 9,
                            Description = "Fresh apples for sale",
                            IsLiked = true,
                            IsOnSale = false,
                            IsPurchased = false,
                            Name = "Apples",
                            PhotograghPath = "",
                            Price = 1.5,
                            Stock = 5,
                            UserId = 1,
                            Weight = 3.0
                        },
                        new
                        {
                            ProduceId = 3,
                            Category = 9,
                            Description = "Organic bananas",
                            IsLiked = false,
                            IsOnSale = true,
                            IsPurchased = false,
                            Name = "Bananas",
                            PhotograghPath = "",
                            Price = 0.98999999999999999,
                            Stock = 10,
                            UserId = 2,
                            Weight = 2.0
                        },
                        new
                        {
                            ProduceId = 4,
                            Category = 9,
                            Description = "Crunchy carrots for cooking",
                            IsLiked = false,
                            IsOnSale = false,
                            IsPurchased = true,
                            Name = "Carrots",
                            PhotograghPath = "",
                            Price = 1.2,
                            Stock = 7,
                            UserId = 2,
                            Weight = 4.0
                        },
                        new
                        {
                            ProduceId = 5,
                            Category = 9,
                            Description = "Juicy red tomatoes",
                            IsLiked = true,
                            IsOnSale = true,
                            IsPurchased = false,
                            Name = "Tomatoes",
                            PhotograghPath = "",
                            Price = 2.75,
                            Stock = 8,
                            UserId = 3,
                            Weight = 3.0
                        },
                        new
                        {
                            ProduceId = 6,
                            Category = 9,
                            Description = "Farm fresh potatoes",
                            IsLiked = false,
                            IsOnSale = false,
                            IsPurchased = false,
                            Name = "Potatoes",
                            PhotograghPath = "",
                            Price = 3.0,
                            Stock = 15,
                            UserId = 3,
                            Weight = 10.0
                        },
                        new
                        {
                            ProduceId = 7,
                            Category = 9,
                            Description = "Sweet strawberries",
                            IsLiked = true,
                            IsOnSale = true,
                            IsPurchased = true,
                            Name = "Strawberries",
                            PhotograghPath = "",
                            Price = 4.5,
                            Stock = 6,
                            UserId = 4,
                            Weight = 1.0
                        },
                        new
                        {
                            ProduceId = 8,
                            Category = 9,
                            Description = "Fresh green lettuce",
                            IsLiked = false,
                            IsOnSale = false,
                            IsPurchased = false,
                            Name = "Lettuce",
                            PhotograghPath = "",
                            Price = 1.1000000000000001,
                            Stock = 4,
                            UserId = 4,
                            Weight = 1.0
                        },
                        new
                        {
                            ProduceId = 9,
                            Category = 9,
                            Description = "Citrus oranges for juice",
                            IsLiked = true,
                            IsOnSale = false,
                            IsPurchased = true,
                            Name = "Oranges",
                            PhotograghPath = "",
                            Price = 2.2999999999999998,
                            Stock = 12,
                            UserId = 5,
                            Weight = 5.0
                        },
                        new
                        {
                            ProduceId = 10,
                            Category = 9,
                            Description = "Cool fresh cucumbers",
                            IsLiked = false,
                            IsOnSale = true,
                            IsPurchased = false,
                            Name = "Cucumbers",
                            PhotograghPath = "",
                            Price = 1.8,
                            Stock = 9,
                            UserId = 5,
                            Weight = 2.0
                        });
                });

            modelBuilder.Entity("VEGG.TABLE.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "bossman@live.co.uk",
                            Name = "VegManDan",
                            Password = "$2a$11$.L.EhNZir7n.hylCEenduOkBlqrdyXHt0jtDqMrW46jy0.pKbkMw2",
                            UserType = 1
                        });
                });

            modelBuilder.Entity("VEGG.TABLE.Core.Entities.UserProduceLike", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ProduceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LikedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "ProduceId");

                    b.HasIndex("ProduceId");

                    b.ToTable("LikedTable");
                });

            modelBuilder.Entity("VEGG.TABLE.Core.Entities.UserProduceLike", b =>
                {
                    b.HasOne("VEGG.TABLE.Core.Entities.Produce", "Produce")
                        .WithMany()
                        .HasForeignKey("ProduceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VEGG.TABLE.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produce");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
