<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\tests\VEGG.TABLE.UnitTests\VEGG.TABLE.UnitTests.csproj" />
    <ProjectReference Include="..\VEGG.TABLE.Client\VEGG.TABLE.Client.csproj" />
    <ProjectReference Include="..\VEGG.TABLE.Core\VEGG.TABLE.Core.csproj" />
    <ProjectReference Include="..\VEGG.TABLE.Infrastructure\VEGG.TABLE.Infrastructure.csproj" />
  </ItemGroup>
</Project>